# .travis.yml
language:
  - python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
notifications:
  - email: fabiomadeira@me.com
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -m unittest discover; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then python -m unittest discover; fi
  - coverage run --source=pdbe setup.py test
after_success:
  - coveralls